### PR TITLE
add salt

### PR DESCRIPTION
**Pull request by salt114514**

### CODE REVIEW

**Comment by Patrick-Star-CN** [comment]
oh, super man salt

**Comment by cmx27** [comment]
oh, super man salt

**Comment by zjuter** [comment]
Salt used to recommend herself :"I'm super salt ,the more I f**ked , the more I'm stronger." The five star up general MacArthur used to recomend :"If I have to face salt ,I'd rather like to face the god"

**Comment by Patrick-Star-CN** [comment]
> Salt used to recommend herself :"I'm super salt ,the more I f**ked , the more I'm stronger." The five star up general MacArthur used to recomend :"If I have to face salt ,I'd rather like to face the god"

wow

**Comment by zhullyb** [comment]
https://github.com/zjutjh/hello-members/commit/2a8f1f9b9a9b1a292fa7579aec7e5db80ae78966

**Pull request closed without merging**
