### PR TITLE
Update members.md

### PR DESCRIPTION
**Pull request by wsm000**
update two new memebers

### CODE REVIEW

**Comment by lixiao189** [comment]
这就对了

**Comment by wsm000** [comment]
what should i do next?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Node ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjutjh/hello-members] Update members.md (PR #151)





 
这就对了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lixiao189** [comment]
接下来不用做了，结束了

**Comment by wsm000** [comment]
it‘s a good news .thanks

**Pull request merged**
